jdk:
  - openjdk11  # 必须指定 JDK 版本（即使不需要编译）

settings:
  install: skip  # 跳过安装阶段
  
before_install:
  - echo "Preparing JAR file..."
  - mkdir -p build/libs
  - cp ts-v3.jar build/libs/ts-v3.jar  # 确保文件名格式正确
  
artifacts:
  - build/libs/ts-v3.jar  # 明确声明要发布的构件
